import { writeFile } from 'node:fs/promises';
import sharp from 'sharp';

const SOURCE = 'src/assets/hero/denis-cutout-640.webp';
const OUT = 'src/seo/ascii-portrait.ts';
const COLS = 72;
// Monospace cells are about twice as tall as wide, so half the rows keep the face proportions.
const ROWS = 36;
// Dense to sparse: darker pixels get heavier glyphs. No '>' so the art can never close an HTML comment.
const RAMP = '@%#*+=-:. ';

const { data, info } = await sharp(SOURCE)
  .resize(COLS, ROWS, { fit: 'fill' })
  .normalise()
  .ensureAlpha()
  .raw()
  .toBuffer({ resolveWithObject: true });

const lines: string[] = [];
for (let y = 0; y < info.height; y++) {
  let line = '';
  for (let x = 0; x < info.width; x++) {
    const i = (y * info.width + x) * 4;
    const [r = 0, g = 0, b = 0, a = 0] = [data[i], data[i + 1], data[i + 2], data[i + 3]];
    if (a < 60) {
      line += ' ';
      continue;
    }
    const luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b;
    line += RAMP[Math.min(RAMP.length - 1, Math.floor((luminance / 256) * RAMP.length))];
  }
  lines.push(line.trimEnd());
}
while (lines[0] === '') lines.shift();
while (lines.at(-1) === '') lines.pop();

const art = lines.join('\n');
await writeFile(OUT, `// Generated by scripts/build-ascii-portrait.ts from the hero portrait.\nexport const ASCII_PORTRAIT = ${JSON.stringify(art)};\n`);
console.log(art);
console.log(`${OUT}: ${lines.length} lines, ${art.length} chars`);
